name: Test
on:
  push:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup environment for Flutter
        uses: subosito/flutter-action@v1
        with: 
          channel: stable

      - name: Enable flutter web
        run: flutter config --enable-web
      
      - name: Get all packages
        run: flutter pub get
      
      - name: Run flutter tests
        run: flutter test